name: Bump Version and Update Changelog for Backend

on:
  push:
    branches:
      - develop
      - homolog
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install setuptools semantic-version

      - name: Bump version in setup.py
        run: |
          branch_name=$(echo "${GITHUB_REF}" | sed 's|refs/heads/||')
          if [[ "$branch_name" == "develop" ]]; then
            version_suffix="-dev"
          elif [[ "$branch_name" == "homolog" ]]; then
            version_suffix="-rc"
          elif [[ "$branch_name" == "main" ]]; then
            version_suffix=""
          fi
          current_version=$(grep "version=" backend/src/camara_de_curitiba/setup.py | sed -E 's/.*version="([^"]+)".*/\1/')
          new_version=$(python -c "import semantic_version; print(semantic_version.Version('$current_version').next_patch())")
          sed -i "s/version=\"$current_version\"/version=\"$new_version$version_suffix\"/" backend/src/camara_de_curitiba/setup.py

      - name: Update CHANGELOG.md
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline > backend/CHANGELOG.md

      - name: Create a new branch
        id: create_branch
        run: |
          branch_name="bump-backend-version-$GITHUB_RUN_ID"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout -b "$branch_name"
          git add backend/src/camara_de_curitiba/setup.py backend/CHANGELOG.md
          git commit -m "Bump backend version and update changelog"
          git push origin "$branch_name"

      - name: Create and merge pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bump-backend-version-${{ github.run_id }}
          base: develop
          title: "Bump Backend Version and Update Changelog"
          body: "This PR updates the version in 'setup.py' and regenerates the 'CHANGELOG.md'."
          labels: "automated"
          auto-merge: true
  draft-release:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: backend-release-drafter.yml
